### ISSUE TITLE
Error when import flowkit

### ISSUE THREAD

**Issue by Legend94rz** [whitews/FlowKit#30] opened 2019-11-02 13:25 UTC
>>> import flowkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\flowkit\__init__.py", line 2, in <module>
    from .models.gate import GatingStrategy
  File "D:\Anaconda3\lib\site-packages\flowkit\models\gate.py", line 9, in <module>
    from flowkit.resources import gml_schema
  File "D:\Anaconda3\lib\site-packages\flowkit\resources\__init__.py", line 18, in <module>
    gml_tree
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}group', attribute 'ref': The QName value '{http://www.isac-net.org/std/Gating-ML/v2.0/transformations}Transformation_Group' does not resolve to a(n) model group definition., line 51

-----------------------
My Environment:
python  3.7
FlowIO                             0.9.5
FlowKit                            0.1.0
flowutils                          0.7.0
lxml                               4.4.1
Windows 10 1903

**Comment by whitews** [comment] 2019-11-02 14:04
Thanks for reporting this. I was able to replicate in a Windows 10 VM. I have an idea as to what the issue is and will provide an update as soon as it is fixed.
-Scott

**Comment by whitews** [comment] 2019-11-02 15:30
This should be fixed in the latest master branch. Can you clone from Github and verify?

**Closed** 2019-11-03 01:00 UTC
Labels: bug

**Comment by Legend94rz** [comment] 2019-11-03 01:39
Yeah, it works. Thanks!

**Comment by whitews** [comment] 2019-11-03 02:11
Great, thanks for verifying. I've released a new version (0.2.0) with this fix and many other improvements. I've updated the version in PyPi as well.

**Comment by ernstdarsac** [comment] 2020-10-28 13:05
I have exactly the same issue using:

python 3.7
FlowIO 0.9.8
FlowKit 0.5.0
flowutils 0.8.0
lxml 4.6.1
Windows 10 1809

Sorry if I am not posting to the right place, I am not very used to github yet.

**Comment by whitews** [comment] 2020-10-28 14:17
@ernstdarsac Thanks for reporting it. Can you post as a new issue and include a full stack trace of the error? It will be easier for both of us to track it in a new issue.

**Comment by ernstdarsac** [comment] 2020-10-28 14:48
> @ernstdarsac Thanks for reporting it. Can you post as a new issue and include a full stack trace of the error? It will be easier for both of us to track it in a new issue.

@whitews Thank you very much, I have opened the new issue with the full error trace. Issue #56
