### ISSUE TITLE
Import Problem Flowkit 0.9.0

### ISSUE THREAD

**Issue by Konsiro** [whitews/FlowKit#106] opened 2022-05-27 07:20 UTC
**Describe the bug**
I have problems with importing the new Flowkit version

**Code To Reproduce**
import flowkit as fk
import bokeh
import bokeh.plotting as show
fcs_path = r"data.fcs"
sample = flowkit.load_samples(fcs_path)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Python version 3.7.13 ( I also tried 3.9 same issue)
 - FlowKit version 0.9.0
 - Flowutils 1.0.0
 - flowio 1.0.1
 - lxml version 4.8.0 

**Additional context**
I used C-compiler from anaconda in an conda vitualenv, my IDLE is Pycharm

Thank you for solving!

**Comment by whitews** [comment] 2022-05-27 13:20
Hi Konsiro,

It's unclear what you mean. Are you having issues import the FlowKit library? If so what error are you getting? If you can paste a complete trace of the error that would be ideal.

**Comment by Konsiro** [comment] 2022-05-27 18:58
Hi,
I am sorry I am new here.
I get this error:

Traceback (most recent call last):
  File "C:/Users...py", line 1, in <module>
    import flowkit as fk
  File "C:\Users\...\anaconda3\envs\FlowCytometerConda\lib\site-packages\flowkit\__init__.py", line 10, in <module>
    from ._models.session import Session
  File "C:\Users\....\anaconda3\envs\FlowCytometerConda\lib\site-packages\flowkit\_models\session.py", line 18, in <module>
    from .._utils import plot_utils, xml_utils, wsp_utils, sample_utils
  File "C:\Users\...\anaconda3\envs\FlowCytometerConda\lib\site-packages\flowkit\_utils\xml_utils.py", line 7, in <module>
    from .._resources import gml_schema
  File "C:\Users\....\anaconda3\envs\FlowCytometerConda\lib\site-packages\flowkit\_resources\__init__.py", line 23, in <module>
    gml_tree
  File "src\lxml\xmlschema.pxi", line 89, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}group', attribute 'ref': The QName value '{http://www.isac-net.org/std/Gating-ML/v2.0/transformations}Transformation_Group' does not resolve to a(n) model group definition., line 5

**Comment by Konsiro** [comment] 2022-05-27 18:59
line 51 instead of line 5

**Comment by whitews** [comment] 2022-05-27 19:29
Hi Konsiro, did a previous version of FlowKit work for you?

**Comment by Konsiro** [comment] 2022-05-27 20:25
Hi whitews, unfortunately not. I saw this issue before and I tried to replicate the versions, but nothing works.

**Comment by whitews** [comment] 2022-05-27 20:39
Ok, from the error it looks to be related to XML. I don't believe it is the version of lxml b/c I am using the same version as you. Just to cover the simple things, do both FlowIO and FlowUtils import for you without errors?

**Comment by whitews** [comment] 2022-05-27 23:29
Also, if you can tell me exactly the steps you used to install FlowKit, I can try to replicate the issue on my end.

Thanks,
Scott

**Comment by whitews** [comment] 2022-05-28 00:41
Konsiro,

I wiped Anaconda and reinstalled on a Windows 10 VM, then created a new conda environment and installed FlowKit via pip. I was then able to import the library without error, so I'm kind of at a loss as to how to replicate the error you are seeing.

**Comment by Konsiro** [comment] 2022-05-28 16:40
FlowIO and FlowUtils seemed to work normally. I really don't know what is wrong probably its just my Windows10 or something else, I have to use another package to work with the fcs files than. Thank you for taking your time.

**Comment by whitews** [comment] 2022-06-04 00:54
Hi Konsiro,

Sorry it's been busy week and I haven't gotten back to you. Sorry you are having issues getting FlowKit to work. I can only think that either you have a corrupt cached flowkit wheel or maybe you have some different CPU architecture? Are you on an Intel or AMD CPU?

You could try:

- forcing a re-download instead of using a cached version using the `--no-cache-dir` option for pip
- making sure pip is upgraded to the latest version using `pip install -U pip`

**Comment by whitews** [comment] 2022-06-07 02:07
Closing this for now. Konsiro, if you ever find out what the issue was, let me know. Hope you'll try FlowKit again in the future.
Regards,
Scott

**Closed by whitews** 2022-06-07 02:07 UTC

**Comment by whitews** [comment] 2022-08-31 18:23
Hi Konsiro,

Another user reported this same error & I was finally able to determine the root cause: it occurs when FlowKit is installed in a location where the directory path contains a "special" character (i.e. accented letters). 

I noticed in your pasted trace that the paths are edited. It's been a while since you reported this, but I'm wondering if you can verify whether your path contained any accented or special characters?

Many thanks in advance,
Scott
