### ISSUE TITLE
RuntimeWarning upon importing a FlowJo .wsp file

### ISSUE THREAD

**Issue by huivni84** [whitews/FlowKit#145] opened 2023-02-09 12:07 UTC
When I try to import a FlowJo workspace (v10.8.1) according to the instructions [Programmatically Replicate Gating from a FlowJo Workspace](https://github.com/whitews/FlowKit/blob/0.9.3/docs/notebooks/advanced/flowkit-session-replicate-flowjo-wsp.ipynb), I get the following error:

```
[...]\flowkit\_models\transforms\_wsp_transforms.py", line 68
    width = np.log10(-low_scale)
RuntimeWarning: divide by zero encountered in log10

Warning (from warnings module):
  File "[...]\flowkit\_models\transforms\_wsp_transforms.py", line 79
    zero_point = int((extra * channel_range) / (extra + decades))
RuntimeWarning: invalid value encountered in scalar add
Traceback (most recent call last):
  File "[...]\flowkit\_models\session.py", line 231, in import_flowjo_workspace
    wsp_sample_groups = wsp_utils.parse_wsp(workspace_file_or_path, ignore_transforms=ignore_transforms)
  File "[...]\flowkit\_utils\wsp_utils.py", line 504, in parse_wsp
    wsp_samples = _parse_wsp_samples(sample_els, ns_map, gating_ns, transform_ns, data_type_ns)
  File "[...]\flowkit\_utils\wsp_utils.py", line 415, in _parse_wsp_samples
    sample_xform_lut = _parse_wsp_transforms(transforms_el, transform_ns, data_type_ns)
  File "[...]\flowkit\_utils\wsp_utils.py", line 173, in _parse_wsp_transforms
    xforms_lut[param_name] = _wsp_transforms.WSPBiexTransform(
  File "[...]\flowkit\_models\transforms\_wsp_transforms.py", line 215, in __init__
    x, y = generate_biex_lut(neg=self.negative, width_basis=self.width, pos=positive, max_value=max_value)
  File "[...]\flowkit\_models\transforms\_wsp_transforms.py", line 79, in generate_biex_lut
    zero_point = int((extra * channel_range) / (extra + decades))
ValueError: cannot convert float NaN to integer
```
Should I transform the data into FlowJo beforehand or am I missing something else? I am mainly interested in replicating the gating strategy.

Any advice would be helpful.

**Comment by whitews** [comment] 2023-02-09 12:58
Hi,

Looks like an issue parsing the bi-exponential transform parameters. Is it possible to share the wsp file?

-Scott

**Comment by whitews** [comment] 2023-02-10 13:51
I understand, but that does make things tricky to figure out the problem. You could share with me privately if that would work.

The issue is that the transformation definitions are sprinkled throughout the XML of the wsp file. If you could make a simpler copy of the wsp in FlowJo by deleting say all but one sample. Then try and replicate the error with that simpler version. If you can replicate the error this way, let me know and I can walk you through copying and pasting the transform portion of the XML text.

**Comment by huivni84** [comment] 2023-02-17 09:39
Hi,

sorry for the late reply.

It looks like the issue was/is caused by file paths. I copied the files to another location to create simpler copies. Interestingly, the error did not occur even with the wsp-file once I opened it in FlowJo and saved it without making changes.

Also pointing in the direction of file paths, now an error occurs that says

```
UserWarning: Sample xy.fcs has not been added to the session. 
A GatingStrategy was loaded for this sample ID, but the file needs to be added to the Session prior to running the analyze_samples method.
```
where _xy_ is a four-digit number instead of the file name.

These numbers appear in the wsp-file next to the actual files paths. Now I remember that when I loaded these files into FlowJo the first time, these numbers appeared instead of the actual sample IDs. This suggests, at least for me, that somewhere in the pipeline a problem with the relation sample ID-file path arose. And I guess, the problem comes from either the software of the FACS device or during the import into FlowJo, which means, it is not related to FlowKit.

**Comment by whitews** [comment] 2023-02-17 13:34
Thanks for the update. I am still concerned that the traceback in your original post points to an issue parsing the bi-ex transform parameters in the wsp file. I'll close this for now, but if that error pops up again feel free to reopen this issue.

**Closed by whitews** 2023-02-17 13:34 UTC
